# Generated by Django 3.0.4 on 2020-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.CharField(max_length=200)),
                ('creation', models.DateTimeField(verbose_name='creation')),
                ('age', models.IntegerField()),
                ('covid', models.BooleanField()),
                ('UID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
